name: Build

on:
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}


jobs:
  GetOutputPaths:
    name: Determine the path into which results for this branch will be written.
    runs-on: ubuntu-latest
    outputs:
      output_path: ${{ steps.get_output_path.outputs.output_path }}
      wiki_hw_diff_path: ${{ steps.get_output_path.outputs.wiki_hw_diffs }}
      wiki_xemu_diff_path: ${{ steps.get_output_path.outputs.wiki_xemu_diffs }}
      site_hw_diff_path: ${{ steps.get_output_path.outputs.site_hw_diffs }}
      site_xemu_diff_path: ${{ steps.get_output_path.outputs.site_xemu_diffs }}
      site_output_path: ${{ steps.get_output_path.outputs.site_output_path }}
      branch: ${{ steps.get_output_path.outputs.branch }}
    steps:
      - name: Get wiki output path
        id: get_output_path
        run: |
          set -x
          branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}
          echo "branch=${branch}" >> $GITHUB_OUTPUT
          # Replace any path separator characters in the branch name for 
          # artifact outputs.
          branch="${branch//\//_}"
          echo "output_path=wiki/${branch}" >> $GITHUB_OUTPUT 
          echo "wiki_hw_diffs=wiki/${branch}/compare_hw" >> $GITHUB_OUTPUT 
          echo "wiki_xemu_diffs=wiki/${branch}/compare_xemu" >> $GITHUB_OUTPUT 
          echo "site_output_path=site/${branch}" >> $GITHUB_OUTPUT 
          echo "site_hw_diffs=site/${branch}/compare_hw" >> $GITHUB_OUTPUT 
          echo "site_xemu_diffs=site/${branch}/compare_xemu" >> $GITHUB_OUTPUT 

  GenerateHardwareDiffs:
    needs: [ GetOutputPaths ]
    name: Generate diffs between the dev results and Xbox hardware results
    runs-on: ubuntu-latest
    timeout-minutes: 45
    outputs:
      hw_diff_artifact: ${{ steps.archive_results.outputs.archive_artifact }}
    steps:
      - name: Clone tree
        uses: actions/checkout@v4
        with:
          fetch-depth: '1'
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
      - name: Install requirements
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            perceptualdiff

          export PIP_BREAK_SYSTEM_PACKAGES=1
          pip3 install -r requirements.txt
          pip3 install -r .github/scripts/requirements.txt
      - name: Generate new diffs
        run: |
          set -x
          python3 .github/scripts/generate_missing_hw_diffs.py --output-dir "${{ needs.GetOutputPaths.outputs.wiki_hw_diff_path }}"
      - uses: actions/upload-artifact@v4
        with:
          name: hardware_diffs
          path: "${{ needs.GetOutputPaths.outputs.wiki_hw_diff_path }}/"
          if-no-files-found: warn
          compression-level: 1

  GenerateXemuDiffs:
    needs: [ GetOutputPaths ]
    name: Generate diffs between the dev results and the latest xemu results
    runs-on: ubuntu-latest
    timeout-minutes: 45
    outputs:
      xemu_diff_artifact: ${{ steps.archive_results.outputs.archive_artifact }}
    steps:
      - name: Clone tree
        uses: actions/checkout@v4
        with:
          fetch-depth: '1'
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
      - name: Install requirements
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            perceptualdiff

          export PIP_BREAK_SYSTEM_PACKAGES=1
          pip3 install -r requirements.txt
          pip3 install -r .github/scripts/requirements.txt
      - name: Generate new diffs
        id: generate_diffs
        run: |
          set -x
          python3 .github/scripts/generate_xemu_diffs.py --output-dir "${{ needs.GetOutputPaths.outputs.wiki_xemu_diff_path }}"
      - uses: actions/upload-artifact@v4
        with:
          name: xemu_diffs
          path: "${{ needs.GetOutputPaths.outputs.wiki_xemu_diff_path }}/"
          if-no-files-found: warn
          compression-level: 1

  UpdateWiki:
    name: Generate a comparison page in the wiki for the current branch
    needs: [ GetOutputPaths, GenerateHardwareDiffs, GenerateXemuDiffs ]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Clone tree
        uses: actions/checkout@v4
        with:
          fetch-depth: '1'
      - name: Clone wiki
        uses: actions/checkout@v4
        with:
          repository: ${{github.repository}}.wiki
          fetch-depth: '1'
          path: wiki
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
      - uses: actions/download-artifact@v4
        with:
          name: hardware_diffs
          path: "${{ needs.GetOutputPaths.outputs.wiki_hw_diff_path }}"
      - uses: actions/download-artifact@v4
        with:
          name: xemu_diffs
          path: "${{ needs.GetOutputPaths.outputs.wiki_xemu_diff_path }}"
      - name: Generate wiki markdown
        run: |
          set -x
          python3 .github/scripts/update_wiki.py \
            "${{ needs.GetOutputPaths.outputs.wiki_hw_diff_path }}" \
            "${{ needs.GetOutputPaths.outputs.wiki_xemu_diff_path }}" \
            "${{ needs.GetOutputPaths.outputs.branch }}" \
            --output-dir "wiki"
      - name: Commit changes
        run: |
          cd wiki 
          git config --local user.email "$GITHUB_ACTOR+github-actions@users.noreply.github.com"
          git config --local user.name "$GITHUB_ACTOR via action"
          git add .
          git diff-index --quiet HEAD || git commit -m "Auto generated diffs against PR results $GITHUB_RUN_NUMBER - $GITHUB_SHA"
          git push


  UpdateSite:
    name: Generate a comparison page in GitHub Pages for the current branch
    needs: [ GetOutputPaths, GenerateHardwareDiffs, GenerateXemuDiffs ]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      site_sha: ${{ steps.commit.outputs.new_head_commit }}
    steps:
      - name: Clone tree
        uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
      - name: Install requirements
        run: |
          export PIP_BREAK_SYSTEM_PACKAGES=1
          pip3 install -r .github/scripts/requirements.txt
      - uses: actions/download-artifact@v4
        with:
          name: hardware_diffs
          path: "${{ needs.GetOutputPaths.outputs.site_hw_diff_path }}"
      - uses: actions/download-artifact@v4
        with:
          name: xemu_diffs
          path: "${{ needs.GetOutputPaths.outputs.site_xemu_diff_path }}"
      - name: Generate Pages site
        run: |
          set -x
          python3 .github/scripts/update_site.py \
            "${{ needs.GetOutputPaths.outputs.site_hw_diff_path }}" \
            "${{ needs.GetOutputPaths.outputs.site_xemu_diff_path }}" \
            "${{ needs.GetOutputPaths.outputs.branch }}" \
            --output-dir "site"
      - name: Switch to pages-branch to restore existing content
        run: |
          set -x
          git fetch
          git status
          tar -czf updated_site.tgz "${{ needs.GetOutputPaths.outputs.site_output_path }}" .github/
          # Delete in case files that exist in the pages branch were modified.
          rm -rf "${{ needs.GetOutputPaths.outputs.site_output_path }}"
          rm -f site/*.* 
          ls site/
          git switch -f pages-branch || (git checkout main && git checkout -b pages-branch)
          ls site/
          # Delete again in case this branch was already present in the pages-branch
          rm -rf "${{ needs.GetOutputPaths.outputs.site_output_path }}"
          tar -xzf updated_site.tgz
          ls site/
      - name: Regenerate the Pages top level index so it includes the previously generated content.
        run: |
          set -x
          python3 .github/scripts/update_site.py \
            "${{ needs.GetOutputPaths.outputs.site_hw_diff_path }}" \
            "${{ needs.GetOutputPaths.outputs.site_xemu_diff_path }}" \
            "${{ needs.GetOutputPaths.outputs.branch }}" \
            --top-index-only \
            --output-dir "site"
      - name: Commit changes
        id: commit
        run: |
          set -x
          git config --local user.email "$GITHUB_ACTOR+github-actions@users.noreply.github.com"
          git config --local user.name "$GITHUB_ACTOR via action"
          git add site
          git diff-index --quiet HEAD || git commit -m "Update from github action $GITHUB_RUN_NUMBER - $GITHUB_SHA"
          git push -f || git push --set-upstream origin pages-branch -f

          sha_new=$(git rev-parse HEAD)
          echo ${sha_new}
          echo "new_head_commit=${sha_new}" >> $GITHUB_OUTPUT

  DeploySite:
    runs-on: ubuntu-latest
    needs: [ UpdateSite ]
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Print site sha
        run: echo "Site SHA is ${{ needs.UpdateSite.outputs.site_sha }}"
      - name: Clone tree
        uses: actions/checkout@v4
        with:
          ref: ${{ needs.UpdateSite.outputs.site_sha }}
          fetch-depth: 1
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'site'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
